### PR TITLE
Budgetmanagementreceipts details

### PR DESCRIPTION
**Pull request by miskowbs**
Page is up to date, however calendar moving around bug persists in my code. I'll look at Morgans solution as soon as both requests are pulled.

### CODE REVIEW

**Comment by cookmn** [comment]
The bold field categories in the pop up modal (ie acountID, receipts...) should be capitalized.

**Comment by cookmn** [comment]
The save button on the modal shouldn't be blue.

**Comment by cookmn** [comment]
Are accountID and accountCode the same thing?  If so, choose a name and stick with it.  If not, will the person using this know the difference?

**Comment by cookmn** [comment]
accountID is always 0 when you open the details modal.  why?

**Comment by cookmn** [comment]
When setting a processed date, it doesn't pop up a date picker so no matter what you put in there it won't work.  Also, if you create an element originally that doesn't have a processed date, it's processed date is set for 1969 (the earliest date possible).  As far as we can tell, this feature still does not work.

**Comment by miskowbs** [comment]
@cookmn > accountID is always 0 when you open the details modal. why?

I don't have this issue. I have different account codes on each details modal.

**Pull request merged**
